### ISSUE TITLE
Exit fullscreen mode

### ISSUE THREAD

**Issue by RobinGoeree2** [GrandDynamo/OneDrive-Cloud-Player#1]
I would like for preference to close fullscreen mode with a shortkey, on most sites it is by pressing the keys 'F, Esc or F11'.

**Comment by GrandDynamo** [comment]
Thank you for the request.
I will take a look at it soon.

**Comment by GrandDynamo** [comment]
I have problems with LibVLCSharp in WPF with window focussing to be able to get keyboard events working correctly. I try to transition to UWP instead of WPF.

**Comment by GrandDynamo** [comment]
I have implemented this feature. You can expect it to be in the next release.
