### ISSUE TITLE
Sanitize file names

### ISSUE THREAD

**Issue by JohannesKauffmann** [GrandDynamo/OneDrive-Cloud-Player#23]
Who thinks of these names... VideoPlayerPageViewModel.cs already resides in the ViewModels folder, so IMO it's unnecessary to have these long names.

**Comment by GrandDynamo** [comment]
I completely agree. We should rename it.

**Comment by JohannesKauffmann** [comment]
Apparently this is standard practise in MVVM. My goodness...
