### ISSUE TITLE
Adding a Licence

### ISSUE THREAD

**Issue by GrandDynamo** [GrandDynamo/OneDrive-Cloud-Player#28]
We should be adding a license to the project in the near future.

**Comment by Madlyaza** [comment]
any licence is fine for me

**Comment by GrandDynamo** [comment]
@Thejackalphantom and @RubenKuilder.

Do you guys agree on the idea of bringing the project under the GPLv2 license?

**Comment by RubenKuilder** [comment]
> @Thejackalphantom and @RubenKuilder.
> 
> Do you guys agree on the idea of bringing the project under the GPLv2 license?

Absolutely, I agree of bringing the project under the GPLv2 license! :)

**Comment by Thejackalphantom** [comment]
I agree to bring it under the license.

**Comment by GrandDynamo** [comment]
Thanks for replying everyone. I will add the license to the project soon.
