### ISSUE TITLE
Skip video time or go back in video

### ISSUE THREAD

**Issue by RobinGoeree2** [GrandDynamo/OneDrive-Cloud-Player#3]
I would like to go back a few seconds in the video or skip a few seconds in the video, is this possible by pressing the arrow buttons on the keyboard like with Youtube or other video stream sites?

**Comment by GrandDynamo** [comment]
I have problems getting keyboard events to work correctly with LibVLCSharp WPF #1 
I will try to implement this if we get the UWP version to work.
