### ISSUE TITLE
Make timer initialization and reset consistent

### ISSUE THREAD

**Issue by JohannesKauffmann** [GrandDynamo/OneDrive-Cloud-Player#45]
Timers in the videoplayer viewmodel are all over the place.
Initialization should happen either at declaration or the constructor, (un)subscribing when navigating to or from the videopage. This can be either in `InitializeLibVLC()` or `Activate()`/`Deactivate()`. Reset should happen every time a new video is played, which is in `PlayMedia()`.

**Comment by GrandDynamo** [comment]
As far as i can see, timers are already being initialised in the declaration. The `reloadIntervalTimer` is started at 2 locations. One with initialization and one in the reload method. We can reduce this by only starting the timer in the playmedia method i think.
