### ISSUE TITLE
seekbar showing timestamp numbers

### ISSUE THREAD

**Issue by RobinGoeree2** [GrandDynamo/OneDrive-Cloud-Player#8]
When I was testing the new release (released on 23-07-2020) I found out the seekbar is showing timestamp numbers from the video it is playing. Is it possible to make this into human readable numbers like a 'HH:mm:ss' or 'mm:ss' format?

I attached a screenshot for a clearer view:
![image](https://user-images.githubusercontent.com/56107687/88299720-fb6bdc00-cd02-11ea-841d-626916edfcae.png)

**Comment by GrandDynamo** [comment]
I assume you have build the project with https://github.com/GrandDynamo/OneDrive-Cloud-Player/commit/b7fb0c7d13555f768aff794a25a60d61f356baeb as the latest commit am i correct?

**Comment by RobinGoeree2** [comment]
> I assume you have build the project with [b7fb0c7](https://github.com/GrandDynamo/OneDrive-Cloud-Player/commit/b7fb0c7d13555f768aff794a25a60d61f356baeb) as the latest commit am i correct?

Yes that is the last commit in the pull history.

**Comment by JohannesKauffmann** [comment]
Suppose this can be closed then.
